# Generated by Django 4.2.13 on 2024-05-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('introduce', models.TextField()),
            ],
        ),
    ]
